### ISSUE TITLE
retrofit2-kotlin-coroutines-adapter cannot be used with Kotlin 1.3-M2

### ISSUE THREAD

**Issue by juergenzimmermann** [JakeWharton/retrofit2-kotlin-coroutines-adapter#19]
After upgrading from Kotlin 1.3-M1 to 1.3-M2 I get this compilation error:
```
Class com.jakewharton.retrofit2.adapter.kotlin.coroutines.CoroutineCallAdapterFactory is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
```

Screenshot:
![grafik](https://user-images.githubusercontent.com/734334/44837222-5260f780-ac39-11e8-81ce-f52683e2743e.png)
