### PR TITLE
Update dependencies for Kotlin 1.3-M2

### LINKED ISSUE #19: retrofit2-kotlin-coroutines-adapter cannot be used with Kotlin 1.3-M2
After upgrading from Kotlin 1.3-M1 to 1.3-M2 I get this compilation error:
```
Class com.jakewharton.retrofit2.adapter.kotlin.coroutines.CoroutineCallAdapterFactory is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
```

Screenshot:
grafik

### PR DESCRIPTION
**Pull request by ryansname**
- Update Kotlin version to 1.3-M2
- Update kotlinx.coroutines-core to 0.25.3-eap13

Fixes #19

### CODE REVIEW

**Comment by JakeWharton** [comment]
Thanks! I'll release later or tomorrow or Monday

**Comment by MGaetan89** [comment]
Any news on this update?

**Comment by JakeWharton** [comment]
Tomorrow. I have other releases to make as well. Thanks for the poke!
